;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Action.Attack.Normal",DevComment="")
+GameplayTagList=(Tag="Action.Attack.Skill1",DevComment="")
+GameplayTagList=(Tag="Action.Attack.Skill2",DevComment="")
+GameplayTagList=(Tag="Boss.Pattern.AntiClose.BackAndThrow",DevComment="")
+GameplayTagList=(Tag="Boss.Pattern.AntiClose.Combo",DevComment="")
+GameplayTagList=(Tag="Boss.Pattern.AntiClose.Lightning",DevComment="")
+GameplayTagList=(Tag="Boss.Pattern.AntiRear",DevComment="")
+GameplayTagList=(Tag="Boss.Pattern.AoE",DevComment="")
+GameplayTagList=(Tag="Boss.Pattern.BasicAttack",DevComment="")
+GameplayTagList=(Tag="Boss.Pattern.ComboAttack",DevComment="")
+GameplayTagList=(Tag="Boss.Pattern.RangedPressure.DarkStone",DevComment="")
+GameplayTagList=(Tag="Boss.Pattern.RangedPressure.Throw",DevComment="one Throw")
+GameplayTagList=(Tag="Boss.Pattern.RangedPressure.TripleThrow",DevComment="")
+GameplayTagList=(Tag="Boss.Pattern.Rush",DevComment="")
+GameplayTagList=(Tag="Boss.Pattern.Summon.Golem",DevComment="")
+GameplayTagList=(Tag="Boss.Pattern.TimeCycle.DarkStone",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Melee",DevComment="")
+GameplayTagList=(Tag="Monster.Boss.Wood",DevComment="")
+GameplayTagList=(Tag="Monster.Normal.Golem",DevComment="")
+GameplayTagList=(Tag="Wood.Pattern.AntiClose.Explosive1",DevComment="구체 폭발")
+GameplayTagList=(Tag="Wood.Pattern.AntiClose.Loop1",DevComment="지속 구체")
+GameplayTagList=(Tag="Wood.Pattern.AoE",DevComment="")
+GameplayTagList=(Tag="Wood.Pattern.BasicAttack",DevComment="")
+GameplayTagList=(Tag="Wood.Pattern.Combo1",DevComment="")
+GameplayTagList=(Tag="Wood.Pattern.RangedPressure.Beam",DevComment="")
+GameplayTagList=(Tag="Wood.Pattern.Rush",DevComment="")
+GameplayTagList=(Tag="Wood.Pattern.Summon.Golem",DevComment="")

